const express = require("express");

const app = express();
app.use(express.json());

app.get("/", (req, res) => {
  res.send("Dakota AI Builder is running");
});

function generateSite(prompt = "basic website") {
  const safeTitle = prompt
    .replace(/[^a-zA-Z0-9 ]/g, "")
    .trim()
    .slice(0, 60) || "Generated Site";

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${safeTitle}</title>
  <style>
    body {
      margin: 0;
      font-family: Arial, sans-serif;
      background: #0f172a;
      color: white;
    }
    .hero {
      min-height: 100vh;
      display: flex;
      align-items: center;
      justify-content: center;
      padding: 40px;
      text-align: center;
      background: linear-gradient(135deg, #111827, #1d4ed8);
    }
    .box {
      max-width: 800px;
      background: rgba(255,255,255,0.08);
      padding: 40px;
      border-radius: 20px;
      box-shadow: 0 10px 30px rgba(0,0,0,0.3);
    }
    h1 {
      font-size: 3rem;
      margin-bottom: 20px;
    }
    p {
      font-size: 1.2rem;
      line-height: 1.6;
      margin-bottom: 30px;
    }
    .btn {
      display: inline-block;
      padding: 14px 24px;
      border-radius: 10px;
      background: #22c55e;
      color: black;
      text-decoration: none;
      font-weight: bold;
    }
  </style>
</head>
<body>
  <section class="hero">
    <div class="box">
      <h1>${safeTitle}</h1>
      <p>This page was generated by Dakota AI Builder from the prompt: "${safeTitle}"</p>
      <a href="#" class="btn">Get Started</a>
    </div>
  </section>
</body>
</html>`;

  return {
    title: safeTitle,
    html
  };
}

app.get("/run", (req, res) => {
  const command = req.query.command;

  if (!command) {
    return res.json({
      status: "error",
      message: "No command provided"
    });
  }

  res.json({
    status: "success",
    command
  });
});

app.get("/generate-site", (req, res) => {
  const prompt = req.query.prompt || "basic website";
  const site = generateSite(prompt);

  res.json({
    status: "success",
    prompt,
    site
  });
});

app.get("/preview-site", (req, res) => {
  const prompt = req.query.prompt || "basic website";
  const site = generateSite(prompt);

  res.setHeader("Content-Type", "text/html");
  res.send(site.html);
});

const PORT = process.env.PORT || 3000;

app.listen(PORT, () => {
  console.log("Server running on port", PORT);
});
