import express from "express";
import cors from "cors";
import archiver from "archiver";

const app = express();
const PORT = process.env.PORT || 3000;

app.use(cors());
app.use(express.json());

function slugify(text) {
  return String(text || "app")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "") || "app";
}

function createProject(prompt) {

  const name = slugify(prompt);

  const html = `<!DOCTYPE html>
<html>
<head>
<title>${prompt}</title>
<link rel="stylesheet" href="style.css">
</head>
<body>

<h1>${prompt}</h1>
<p>Generated by Dakota AI Builder</p>

<button onclick="alert('App working')">
Click Me
</button>

<script src="script.js"></script>

</body>
</html>`;

  const css = `
body{
font-family:Arial;
background:#0f172a;
color:white;
text-align:center;
padding:60px;
}

button{
padding:15px 25px;
font-size:18px;
background:#22c55e;
border:none;
border-radius:8px;
cursor:pointer;
}
`;

  const js = `
console.log("${prompt} running");
`;

  return {
    projectName: name,
    files: {
      "index.html": html,
      "style.css": css,
      "script.js": js
    }
  };
}

app.get("/", (req,res)=>{
res.send("Dakota AI Builder running");
});

app.get("/health",(req,res)=>{
res.json({
status:"online",
system:"Dakota AI Builder"
});
});

app.post("/create-app",(req,res)=>{

const prompt = req.body?.prompt || "starter app";

const project = createProject(prompt);

res.json(project);

});

app.get("/download-app",(req,res)=>{

const prompt = req.query.prompt || "starter app";

const project = createProject(prompt);

const archive = archiver("zip",{zlib:{level:9}});

res.setHeader("Content-Type","application/zip");
res.setHeader("Content-Disposition",`attachment; filename="${project.projectName}.zip"`);

archive.pipe(res);

for(const [file,content] of Object.entries(project.files)){
archive.append(content,{name:file});
}

archive.finalize();

});

app.post("/deploy",(req,res)=>{

const prompt = req.body?.prompt || "app";

const project = createProject(prompt);

res.json({
status:"deployment module ready",
project:project.projectName,
message:"Next step will push this to hosting"
});

});

app.listen(PORT,()=>{
console.log("Dakota AI Builder running on port",PORT);
});
