import express from "express";
import cors from "cors";

const app = express();

app.use(cors());
app.use(express.json());

const PORT = process.env.PORT || 3000;

/* ------------------------------
   Health check (server status)
--------------------------------*/

app.get("/health", (req, res) => {
  res.json({
    status: "online",
    system: "Dakota AI Builder",
    version: "1.0"
  });
});

/* ------------------------------
   Root route
--------------------------------*/

app.get("/", (req, res) => {
  res.send(`
  <html>
  <head>
  <title>Dakota AI Builder</title>
  <style>
  body{
    background:#0f172a;
    color:white;
    font-family:Arial;
    text-align:center;
    padding:40px;
  }

  button{
    background:#22c55e;
    border:none;
    padding:12px 20px;
    border-radius:8px;
    color:white;
    font-size:18px;
    cursor:pointer;
  }

  .card{
    background:#1e293b;
    padding:30px;
    border-radius:10px;
    max-width:600px;
    margin:auto;
  }
  </style>
  </head>

  <body>

  <div class="card">
  <h1>Dakota AI Builder</h1>
  <p>Automated AI App Builder System</p>

  <button onclick="buildSite()">Build Example App</button>

  <pre id="result"></pre>
  </div>

  <script>

  async function buildSite(){

  const res = await fetch('/create-app',{
  method:'POST',
  headers:{'Content-Type':'application/json'},
  body:JSON.stringify({
  prompt:'affiliate comparison site'
  })
  })

  const data = await res.json()

  document.getElementById("result").textContent =
  JSON.stringify(data,null,2)

  }

  </script>

  </body>
  </html>
  `);
});

/* ------------------------------
   AI Builder endpoint
--------------------------------*/

app.post("/create-app", async (req, res) => {

  const { prompt } = req.body;

  const projectName = prompt.replace(/\s/g, "-").toLowerCase();

  const files = {
    "index.html": `
<!DOCTYPE html>
<html>
<head>
<title>${prompt}</title>
<style>
body{
font-family:Arial;
background:#0f172a;
color:white;
text-align:center;
padding:40px;
}
button{
background:#22c55e;
border:none;
padding:12px 20px;
border-radius:8px;
color:white;
font-size:18px;
}
</style>
</head>

<body>

<h1>${prompt}</h1>
<p>Generated by Dakota AI Builder</p>

<button>Start</button>

</body>
</html>
`
  };

  res.json({
    status: "success",
    projectName,
    prompt,
    files
  });

});

/* ------------------------------
   Start server
--------------------------------*/

app.listen(PORT, () => {
  console.log("Dakota AI Builder running on port", PORT);
});
